paypal_ipn: https://my-website/civicrm/payment/ipn/2/

external:
  enabled: false
  api_key:
  site_key:
  rest_url: 'https://my-website/civicrm/ajax/rest'

gravity_forms:
  1:
    contact:
      entries:
        first_name: '1.3'
        last_name: '1.6'
    email:
      entries:
        email: '2'
    tags:
      values:
        - 'Company'
        - 'Non-profit'
      entries:
        - '10'
    groups:
      values:
        - 'Administrators'
        - 'Newsletter Subscribers'
      entries:
        - '9.1'
        - '9.2'
    subscribe:
      value: 26
      entry: '10'
    contribution:
      is_test: 1
      entries:
        amount: '5'
        frequency_unit: '16'
      financial_type_id: 1
      source: 'Donation form'
      paypal:
        payment_instrument_id: 'Paypal'
        payment_processor_id: 'Paypal'
      stripe:
        payment_instrument_id: 1
        payment_processor_id: 4

elementor:
  contact_form:
    contact:
      entries:
        first_name: 'first_name'
        last_name: 'last_name'
        contact_type: 'contact_type'
        source: 'source'
    email:
      entries:
        email: 'email'
    activity:
      type: 'Inbound Email'
      subject: 'Website contact'
      entries:
        details: 'message'

  newsletter_form:
    contact:
      entries:
        first_name: 'first_name'
        last_name: 'last_name'
        contact_type: 'contact_type'
        source: 'source'
        do_not_email: 'do_not_email'
    email:
      entries:
        email: 'email'
