paypal_ipn: https://my-wp-web-site/civicrm/payment/ipn/2/
gravity_forms:
  1:
    contact:
      entries:
        first_name: '1.3'
        last_name: '1.6'
    email:
      entries:
        email: '2'
    contribution:
      is_test: 1
      entries:
        amount: '5'
        frequency_unit: '16'
      financial_type_id: 1
      source: 'Form di donazione dal sito web ACME'
      paypal:
        payment_instrument_id: 'Paypal'
        payment_processor_id: 'Paypal'
      stripe:
        payment_instrument_id: 1
        payment_processor_id: 4

